dist: trusty
sudo: required
language: java

cache:
  directories:
    - .autoconf
    - $HOME/.m2


services:
  - docker

before_install:
  - docker pull consul
  - docker run -d -p 8500:8500 -p 8600:8600/udp --name=badger consul agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0

script:
  - mvn test -B -P spring

jdk:
  - oraclejdk8
  - openjdk8
