# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: consul
        command: [consul, agent, -server, -ui, -node=server-1, -bootstrap-expect=1, -client=0.0.0.0, --data-dir=/consul/data]
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P spring

      - save_cache:
          paths:
            - ~/.m2
            - .autoconf
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test -B -P spring
