# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: sudo apt remove maven && sudo apt update && sudo apt install maven
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P spring

      - save_cache:
          paths:
            - ~/.m2
            - .autoconf
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn clean install -B -P spring
      - run: bash <(curl -s https://codecov.io/bash)
